# Generated by Django 4.1 on 2022-09-02 15:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='客户称呼')),
                ('_mobile', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('_wechat', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=12, null=True, verbose_name='QQ')),
                ('git', models.URLField(blank=True, null=True, verbose_name='git账户')),
                ('_id_card', models.CharField(blank=True, max_length=64, null=True, verbose_name='身份证')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('source', models.CharField(blank=True, max_length=64, null=True, verbose_name='客户来源')),
            ],
            options={
                'verbose_name': '客户资料',
                'verbose_name_plural': '客户资料',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='详情')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='联系电话')),
                ('contact', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系人')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('wechat', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信号')),
                ('days', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='工时(天)')),
                ('image_hub', models.URLField(blank=True, null=True, verbose_name='镜像仓库')),
                ('code_hub', models.URLField(blank=True, null=True, verbose_name='代码仓库')),
                ('online_url', models.URLField(blank=True, null=True, verbose_name='线上地址')),
                ('finished', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='标定价格')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='xoo.account', verbose_name='客户')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='开发者')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('number', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='金额')),
                ('annotation', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('validate_code', models.CharField(blank=True, max_length=18, null=True, verbose_name='核销码')),
                ('validated_at', models.DateTimeField(null=True, verbose_name='核销时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='xoo.account', verbose_name='客户')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='xoo.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '收据',
                'verbose_name_plural': '收据',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('filename', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='文件链接')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='xoo.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '文件附件',
                'verbose_name_plural': '文件附件',
                'db_table': 'file',
            },
        ),
    ]
